version: '3'
services:
  node:
    build: 
      dockerfile: ./Dockerfile
      context: .
    container_name: gift_me_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    depends_on:
      - "database"

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gift_me
    ports:
      - "33060:3306"